### ISSUE TITLE
[ETI] Basic or Module builds based on what's available in a directory

### ISSUE THREAD

**Issue by nazunalika** [nazunalika/lazybuilder#8]
**What am I trying to solve?**
There are some cases that instead of providing a list of RPM's (in URL form) to build in a chain, it would be simpler to have them already built and downloaded and available to the builder somewhere in `repo_path` - Optionally, we can provide the ability to just build the source RPM's and drop them somewhere or just download them somewhere as needed.

**For Basic Builds**
Chains are all well and good, but we want to provide a way to just provide a directory filled with srpms to build. This is a potential use case for some.

**For Modules**
There are some module builds that are either difficult or impossible to do in the current state. What we want to do is have the ability to do builds based on srpms that are available in the repo directories and go from there, taking into account that the module YAML is still imported from git. So in essence, the following should happen:

* Module vars are setup by looking at the git repo information and the like
* A directory is provided that has the module's name and version number
* During setup, mock_srpm_path will be built as a list, either by:
  * Checking if there are buildgroup-NUMBER directories and building the list based on that, or...
  * Looking at the build group list in the YAML, doing comparisons, and adding as they're found in found directory
* Module is built like normal

**Downloader/srpm builder**

We can provide tasks that will allow us to just build source RPM's and drop them somewhere to be built later or just download them to be used elsewhere. We may want the playbook to look for a dictionary type of var, something like this:

```
build_srpm_list:
  gcc:
    branch: r8
    # Potentially use this to override the location?
    git_url: https://git.rockylinux.org/staging/rpms/gcc.git
    buildorder: 0
  glibc:
    branch: r8
    git_url: https://git.rockylinux.org/staging/rpms/glibc.git
    buildorder: 1
  bash:
    branch: r8
    git_url: https://git.rockylinux.org/staging/rpms/bash.git
    buildorder: 2
  mksh:
    branch: r8
    git_url: https://git.rockylinux.org/staging/rpms/mksh.git
    buildorder: 2
pull_srpm_list:
  kernel:
    url: https://some.url.com/kernel-4.18.0-305.17.1.el8_4.src.rpm
    buildorder: 3
```

**What are the benefits of this?**
Makes life easier of some users or provides the ability to "stage" builds.

**Additional context and information**
Everything above is all we need.
